# roles/nginx/tasks/main.yml
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx for /images
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Enable Nginx
  service:
    name: nginx
    state: restarted

